name: pymks
channels:
  - conda-forge
dependencies:
  - python=3.7
  - sfepy=2019.4
  - scipy=1.4.1
  - dask=2.10.1
  - scikit-learn=0.22.1
  - toolz=0.10.0
  - coverage=4.5.4
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pytest=5.3.5
  - pytest-cov=2.8.1
  - notebook=6.0.3
  - dask-ml=1.2.0
  - nbval=0.9.5
