name: pymks
channels:
  - conda-forge
dependencies:
  - python=3.6
  - sfepy=2018.2
  - scipy=1.2.1
  - dask=1.1.1
  - scikit-learn=0.20.2
  - toolz=0.10.0
  - coverage=4.5.4
  - matplotlib=3.1.1
  - numpy=1.17.1
  - pytest=5.1.1
  - pytest-cov=2.7.1
  - notebook=6.0.1
  - dask-ml=1.0.0
  - nbval=0.9.1
